# Generated by Django 2.1.5 on 2019-10-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_ent_url_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ent_url_data',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
