# Generated by Django 2.1.5 on 2019-10-02 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20191002_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ent_url_data',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today),
        ),
    ]
