# Generated by Django 2.1.5 on 2019-10-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20191002_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ent_url_data',
            name='date_time',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
