# Generated by Django 2.1.5 on 2019-10-03 05:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20191002_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ent_url_data',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
